#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 -v USER="$POSTGRES_USER" -U "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE api;
    GRANT ALL PRIVILEGES ON DATABASE api TO :USER;
    CREATE DATABASE api_test;
    GRANT ALL PRIVILEGES ON DATABASE api_test TO :USER;
EOSQL